steps:
# 1. Docker 이미지 빌드
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/safecutai-repo/safecutai-app'
  - '.'


# 2. Artifact Registry에 이미지 푸시
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/safecutai-repo/safecutai-app']

# 3. Cloud Run에 배포
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'safecutai-app' # Cloud Run 서비스 이름
  - '--image'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/safecutai-repo/safecutai-app'
  - '--region'
  - 'asia-northeast3' # 배포 리전
  - '--allow-unauthenticated' # 인증 없이 액세스 허용
options:
  logging: CLOUD_LOGGING_ONLY